// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Firebase has been configured for Android only.');
    }

    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }

    throw UnsupportedError('Firebase has been configured for Android only.');
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1aU4aSc-5mAGcCgnZiurNnZ6mseZizSo',
    appId: '1:795095246457:android:cd4519b09c1991f4b3d6a8',
    messagingSenderId: '795095246457',
    projectId: 'lab-project-2230e',
    storageBucket: 'lab-project-2230e.firebasestorage.app',
  );
}
